name: Contexts demo
on: [push]

jobs:
 # job name
  github-context:
    runs-on: ubuntu-latest
    steps:
     - name: print info
       run: |
         echo "${{ toJson(github) }}"   # # run till here yu will get all predefined contex names 
         echo "branch name: ${{ github.ref_name }}"