name: Contexts demo
on: [push]

env:
  project: "roboshop"
  component: "catalogue"
  environment: "dev"

jobs:
 # job name
  github-context:
    runs-on: ubuntu-latest
    steps:
     - name: print info
       run: |
         echo "${{ toJson(github) }}"   # # run till here yu will get all predefined contex names 
         echo "branch name: ${{ github.ref_name }}"

     - name: access any variables
       run: |
         echo "Project: $project"
         echo "Component: $component"
         echo "Environment: $environment"

     - name: access the secrets
       run: |
         echo "DB user name:  ${{ secrets.DB_USER }}"
         echo "DB password:  ${{ secrets.DB_PASSWORD }}"
        
     - name: print the variables
       run: |
         echo "DB_URL: ${{ vars.DB_URL }}"


     - name: image tag
       id: tag
       run: |
          echo "version=1.0.0" >> $GITHUB_OUTPUT
          echo "image-name=catalogue" >> $GITHUB_OUTPUT

     - name: print previous step output
       run: |
         echo "Image name: ${{ steps.tag.outputs.image-name }}"
         echo "Version: ${{ steps.tag.outputs.version }}"
        