name: feature-pipeline
on: [push]
jobs:
  feature-pipeline:
    uses: prasanna0805/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with: 
      project: 'roboshop'
      component: 'catalogue'
      environment: 'dev' 